#!/usr/bin/env bash
#Redirects '/redirect_me' page on server (moved permanently)
sed -i '38i\rewrite ^/redirect_me sitesurf.tech permanent;' /etc/nginx/sites-enabled/default
sudo service nginx restart
