#!/usr/bin/env bash
#custom error 404 page
./1-install_nginx_web_server
echo "Ceci n'est pas une page" > /var/www/html/error404.html

sed -i '42i\error_page 404 /error404.html;' /etc/nginx/sites-enabled/default

service nginx restart
