#!/usr/bin/env bash
#custom error 404 page
./3-redirection
echo "Ceci n'est pas une page" > /var/www/html/error404.html

sed '42i\error_page 404 /error404.html;' /etc/nginx/sites-enabled/default

service nginx restart
