#!/usr/bin/env bash
# script to make nginx run and listen on port 80
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sed -i 's/ipv6only=on//g' /etc/nginx/sites-enabled/default
service nginx restart
