#!/usr/bin/env bash
#Displays "Best School" and after 9th iteration says "Hi"
count=0
while (("$count"<10))
do
	echo "Best School"
	if (("$count"==8))
	then
		echo "Hi"
	fi
	count=$((count + 1))
done
