#!/usr/bin/env bash
#Bash script while loop
count=0
while (("$count"<10))
do
	if (("$count"==3))
	then
		echo "bad luck"
	elif (("$count"==7))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	count=$((count + 1))
done
