#!/usr/bin/env bash
#Gives information about the file 'school'
name="school"
if [ -e "$name" ]
then
	echo "$name file exists"
	if [ -s "$name" ]
	then
	echo "$name file is not empty"
	else
	echo "$name file is empty"
	fi
	if [ -f "$name" ]
	then
	echo "$name is a regular file"
	else
	echo ""
	fi
else
	echo "$name file does not exist"
fi
